name: Coveralls

on:
  push:
    branches:
    - main
  pull_request: null

jobs:
  build:
    runs-on: ubuntu-22.04

    name: Send Code Coverage to Coveralls
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: xvfb-run mvn verify -Pjacoco
      working-directory: project.discography

    - name: Send Code Coverage
      uses: coverallsapp/github-action@v2