name: Build CI with Maven on Linux

on:
  push: null

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      workdir: project.discography
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17

    name: Build CI with Maven and Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn verify
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir}}
      if: ${{ failure() }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: surefire-report-Java-${{ matrix.java }}
        path: '**/target/site'