name: Build CI with Maven on MacOS

on:
  push:
    branches:
    - main
  pull_request: null

jobs:
  build:
    runs-on: macos-12
    env:
      workdir: project.discography

    name: Build CI with Maven and Java 8
    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn test
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir}}
      if: ${{ failure() }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: surefire-report-MacOS
        path: '**/target/site'